name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Get build version
        shell: pwsh
        run: |
          $version = dotnet fsi .\bin\ParseBuildVersion.fsx $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "BUILD_VERSION=$version"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Add GPR source
        run: dotnet nuget add source --username leydel --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/leydel/index.json"

      - name: Pack project
        run: dotnet pack -p:PackageVersion=${{ env.BUILD_VERSION }} --configuration $BUILD_CONFIG

      - name: Publish package
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
          dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source "nuget.org"
